name: reservatoriosBRbot

on:
  schedule:
  - cron: '0 13 * * *'
  workflow_dispatch:

jobs:
  londonmapbot-post:
    runs-on: macOS-latest
    env:
      TWITTER_CONSUMER_API_KEY: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
      TWITTER_CONSUMER_API_SECRET: ${{ secrets.TWITTER_CONSUMER_API_SECRET }}
      TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
      TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
      GITHUB_PAT: ${{ secrets.PAT_GITHUB }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2

      - name: Install packages
        run: |
          install.packages("remotes")
          remotes::install_cran("rtweet")
          remotes::install_github("brunomioto/reservatoriosBR")          
        shell: Rscript {0}
        
      - name: Create and post tweet
        run: Rscript subsistemas-tweet.R
